language: minimal

services:
  - docker

install:
  - docker build -t bigmak40/catt .

script:
  - docker run --rm --name catt bigmak40/catt --version | grep -c "catt v0.11.3, Xylophone Xtravaganza." || travis_terminate 1
